
/*
CREATE TABLE `NOTICE_CONTENTS` (
	`PK_A`	VARCHAR(50)	NOT NULL,
	`CONTENTS`	VARCHAR(1000)	NULL,
	`WRITER`	VARCHAR(50)	NULL
);

CREATE TABLE `NOTICE_VISITOR` (
	`PK_B`	VARCHAR(50)	NOT NULL,
	`FK_A`	VARCHAR(50)	NOT NULL,
	`VISITOR`	VARCHAR(50)	NULL
);
*/

DELETE FROM `NOTICE_VISITOR` 
WHERE `FK_A`='A_01';

DELETE FROM `NOTICE_VISITOR` 
WHERE `FK_A`='A_01';

DELETE FROM `NOTICE_CONTENTS` 
WHERE `PK_A`='A_01';

--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

DELETE FROM `NOTICE_VISITOR` 
WHERE `FK_A`='A_02';

DELETE FROM `NOTICE_VISITOR` 
WHERE `FK_A`='A_02';

DELETE FROM `NOTICE_VISITOR` 
WHERE `FK_A`='A_02';

DELETE FROM `NOTICE_CONTENTS` 
WHERE `PK_A`='A_02';

--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


DELETE FROM `NOTICE_VISITOR` 
WHERE `FK_A`='A_03';

DELETE FROM `NOTICE_CONTENTS` 
WHERE `PK_A`='A_03';

--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


DELETE FROM `NOTICE_VISITOR` 
WHERE `FK_A`='A_04';

DELETE FROM `NOTICE_VISITOR` 
WHERE `FK_A`='A_04';

DELETE FROM `NOTICE_VISITOR` 
WHERE `FK_A`='A_04';

DELETE FROM `NOTICE_CONTENTS` 
WHERE `PK_A`='A_04';

--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


DELETE FROM `NOTICE_VISITOR` 
WHERE `FK_A`='A_05';

DELETE FROM `NOTICE_VISITOR` 
WHERE `FK_A`='A_05';

DELETE FROM `NOTICE_VISITOR` 
WHERE `FK_A`='A_05';

DELETE FROM `NOTICE_CONTENTS` 
WHERE `PK_A`='A_05';

--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~