CREATE TABLE `RESPONDENTS` (
	`PK_A`	VARCHAR(50)	NOT NULL,
	`RESPONDENT`	VARCHAR(50)	NULL,
	`CORR_COUNT`	VARCHAR(50)	NULL
);

CREATE TABLE `ANSWERS` (
	`PK_B`	VARCHAR(50)	NOT NULL,
	`FK_A`	VARCHAR(50)	NOT NULL,
	`ANSWER`	VARCHAR(50)	NULL
);

CREATE TABLE `QUESTIONS` (
	`PK_Q`	VARCHAR(50)	NOT NULL,
	`QUESTION`	VARCHAR(1000)	NULL,
	`ANSWER`	VARCHAR(50)	NULL
);

CREATE TABLE `OPTIONS` (
	`PK_O`	VARCHAR(50)	NOT NULL,
	`FK_Q`	VARCHAR(50)	NOT NULL,
	`OPTION`	VARCHAR(1000)	NULL
);

ALTER TABLE `RESPONDENTS` ADD CONSTRAINT `PK_RESPONDENTS` PRIMARY KEY (
	`PK_A`
);

ALTER TABLE `ANSWERS` ADD CONSTRAINT `PK_ANSWERS` PRIMARY KEY (
	`PK_B`,
	`FK_A`
);

ALTER TABLE `QUESTIONS` ADD CONSTRAINT `PK_QUESTIONS` PRIMARY KEY (
	`PK_Q`
);

ALTER TABLE `OPTIONS` ADD CONSTRAINT `PK_OPTIONS` PRIMARY KEY (
	`PK_O`,
	`FK_Q`
);

ALTER TABLE `ANSWERS` ADD CONSTRAINT `FK_RESPONDENTS_TO_ANSWERS_1` FOREIGN KEY (
	`FK_A`
)
REFERENCES `RESPONDENTS` (
	`PK_A`
);

ALTER TABLE `OPTIONS` ADD CONSTRAINT `FK_QUESTIONS_TO_OPTIONS_1` FOREIGN KEY (
	`FK_Q`
)
REFERENCES `QUESTIONS` (
	`PK_Q`
);

