name: Update README

on:
  push:
    branches:
      - main  # 또는 원하는 브랜치 이름

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README
        run: |
          echo "## Directory Structure" > README.md  # README 파일 초기화
          echo "Updated on $(date)" >> README.md  # 현재 날짜 추가
          echo "" >> README.md
          echo "\`\`\`" >> README.md  # 코드 블록 시작
          ls -R >> README.md  # 현재 디렉토리 구조 추가
          echo "\`\`\`" >> README.md  # 코드 블록 종료

      - name: Commit changes
        run: |
          git config --local user.email "your-email@example.com"
          git config --local user.name "Your Name"
          git add README.md
          git commit -m "action: update directory structure" || echo "No changes to commit"

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
